# DATA PREPROCESSING/ DATA PREPARATION
### 3 Step Approach:

**1. Data Cleaning: drop, dropna, Mean, median, mode imputation/ any value imputation for NaN values**

**2. DataType Conversion**

**3. Data Tranformation**

## 1. Import Neccessary Libraries

In [1]:
import pandas as pd

## 2. Import data

In [2]:
weather_data_2010 = pd.read_csv('data_clean.csv')
weather_data_2010

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

## 3. Data Understanding

### 3.1. Initial Analysis

In [3]:
weather_data_2010.shape

(158, 10)

In [4]:
weather_data_2010.isna().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [5]:
weather_data_2010.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

## 4. Data Preparation:

###  4.1. Data Cleaning:

In [6]:
weather_data_2010.drop(labels='Unnamed: 0', axis=1, inplace=True)

In [7]:
weather_data_2010.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Temp C      0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [8]:
38/158*100

24.050632911392405

#### Observation:
We can see that there are a lot of null entries in the Ozone feature. 

**Que:**

**1. What could be the reason for so many null values? - assumptions**

**2. Should the null values in the column be replaced by mean/ median or should the null values be dropped completely? --GET THE CLIENTS APPROVAL.**

In [9]:
weather_data_2010['Ozone'].mean()

41.583333333333336

In [10]:
weather_data_2010['Ozone'].median()

30.5

### Assumption: Client has approved to impute NaN values with median values for Ozone feature, drop NaN values for Solar.R and Weather features.

In [11]:
weather_data_2010['Ozone'].fillna(value=30.5, inplace=True)
##MEDIAN IMPUTATION

In [12]:
weather_data_2010.isna().sum()

Ozone      0
Solar.R    7
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [13]:
weather_data_2010.head(40)

    Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0    41.0    190.0   7.4     67     5    1  2010    67       S
1    36.0    118.0   8.0     72     5    2  2010    72       C
2    12.0    149.0  12.6     74     5    3  2010    74      PS
3    18.0    313.0  11.5     62     5    4  2010    62       S
4    30.5      NaN  14.3     56     5    5  2010    56       S
5    28.0      NaN  14.9     66     5    6  2010    66       C
6    23.0    299.0   8.6     65     5    7  2010    65      PS
7    19.0     99.0  13.8     59     5    8  2010    59       C
8     8.0     19.0  20.1     61     5    9  2010    61      PS
9    30.5    194.0   8.6     69     5   10  2010    69       S
10    7.0      NaN   6.9      C     5   11  2010    74       C
11   16.0    256.0   9.7     69     5   12  2010    69      PS
12   11.0    290.0   9.2     66     5   13  2010    66       S
13   14.0    274.0  10.9     68     5   14  2010    68       S
14   18.0     65.0  13.2     58     5   15  2010    58       C
15   14.0    334.0  11.5     64     5   16  2010    64       S
16   34.0    307.0  12.0     66     5   17  2010    66       S
17    6.0     78.0  18.4     57     5   18  2010    57       C
18   30.0    322.0  11.5     68     5   19  2010    68      PS
19   11.0     44.0   9.7     62     5   20  2010    62       S
20    1.0      8.0   9.7     59     5   21  2010    59       S
21   11.0    320.0  16.6     73     5   22  2010    73       C
22    4.0     25.0   9.7     61     5   23  2010    61      PS
23   32.0     92.0  12.0     61   May   24  2010    61       C
24   30.5     66.0  16.6     57     5   25  2010    57      PS
25   30.5    266.0  14.9     58     5   26  2010    58       C
26   30.5      NaN   8.0     57     5   27  2010    57      PS
27   23.0     13.0  12.0     67     5   28  2010    67       S
28   45.0    252.0  14.9     81     5   29  2010    81       S
29  115.0    223.0   5.7     79     5   30  2010    79       C
30   37.0    279.0   7.4     76     5   31  2010    76      PS
31   30.5    286.0   8.6     78     6    1  2010    78       S
32   30.5    287.0   9.7     74     6    2  2010    74       C
33   30.5    242.0  16.1     67     6    3  2010    67      PS
34   30.5    186.0   9.2     84     6    4  2010    84       C
35   30.5    220.0   8.6     85     6    5  2010    85      PS
36   30.5    264.0  14.3     79     6    6  2010    79       C
37   29.0    127.0   9.7     82     6    7  2010    82      PS
38   30.5    273.0   6.9     87     6    8  2010    87       S
39   71.0    291.0  13.8     90     6    9  2010    90       S

In [14]:
weather_data_2010.isna().sum()

Ozone      0
Solar.R    7
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [15]:
7/158*100

4.430379746835443

#### Observation: 
There are very less observations with null values in Solar.R feature. It comprises of only 4% of the data. Hence, it can be dropped, but with client approval only.

**Multiple feature imputation is never a good idea. It may lead to unreal data.**

In [16]:
weather_data_2010.dropna(inplace=True)

In [17]:
weather_data_2010.isna().sum()

Ozone      0
Solar.R    0
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

### 4.2 DataType conversion:

In [18]:
weather_data_2010.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Temp C      object
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [19]:
del weather_data_2010['Temp C']
#OR weather_data_2010.drop(labels='Temp C', axis=1, inplace=True)

In [20]:
weather_data_2010.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [21]:
weather_data_2010['Month'] = pd.to_numeric(weather_data_2010['Month'], errors='coerce') 
#### Any non numeric value gets converted to NaN. By default the numeric values get converted into float.

In [22]:
weather_data_2010.head(40)

    Ozone  Solar.R  Wind  Month  Day  Year  Temp Weather
0    41.0    190.0   7.4    5.0    1  2010    67       S
1    36.0    118.0   8.0    5.0    2  2010    72       C
2    12.0    149.0  12.6    5.0    3  2010    74      PS
3    18.0    313.0  11.5    5.0    4  2010    62       S
6    23.0    299.0   8.6    5.0    7  2010    65      PS
7    19.0     99.0  13.8    5.0    8  2010    59       C
8     8.0     19.0  20.1    5.0    9  2010    61      PS
9    30.5    194.0   8.6    5.0   10  2010    69       S
11   16.0    256.0   9.7    5.0   12  2010    69      PS
12   11.0    290.0   9.2    5.0   13  2010    66       S
13   14.0    274.0  10.9    5.0   14  2010    68       S
14   18.0     65.0  13.2    5.0   15  2010    58       C
15   14.0    334.0  11.5    5.0   16  2010    64       S
16   34.0    307.0  12.0    5.0   17  2010    66       S
17    6.0     78.0  18.4    5.0   18  2010    57       C
18   30.0    322.0  11.5    5.0   19  2010    68      PS
19   11.0     44.0   9.7    5.0   20  2010    62       S
20    1.0      8.0   9.7    5.0   21  2010    59       S
21   11.0    320.0  16.6    5.0   22  2010    73       C
22    4.0     25.0   9.7    5.0   23  2010    61      PS
23   32.0     92.0  12.0    NaN   24  2010    61       C
24   30.5     66.0  16.6    5.0   25  2010    57      PS
25   30.5    266.0  14.9    5.0   26  2010    58       C
27   23.0     13.0  12.0    5.0   28  2010    67       S
28   45.0    252.0  14.9    5.0   29  2010    81       S
29  115.0    223.0   5.7    5.0   30  2010    79       C
30   37.0    279.0   7.4    5.0   31  2010    76      PS
31   30.5    286.0   8.6    6.0    1  2010    78       S
32   30.5    287.0   9.7    6.0    2  2010    74       C
33   30.5    242.0  16.1    6.0    3  2010    67      PS
34   30.5    186.0   9.2    6.0    4  2010    84       C
35   30.5    220.0   8.6    6.0    5  2010    85      PS
36   30.5    264.0  14.3    6.0    6  2010    79       C
37   29.0    127.0   9.7    6.0    7  2010    82      PS
38   30.5    273.0   6.9    6.0    8  2010    87       S
39   71.0    291.0  13.8    6.0    9  2010    90       S
40   39.0    323.0  11.5    6.0   10  2010    87       S
41   30.5    259.0  10.9    6.0   11  2010    93       C
42   30.5    250.0   9.2    6.0   12  2010    92      PS
43   23.0    148.0   8.0    6.0   13  2010    82       S

In [23]:
weather_data_2010.isna().sum()

Ozone      0
Solar.R    0
Wind       0
Month      1
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [24]:
weather_data_2010.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month      float64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [25]:
weather_data_2010['Month'].fillna(value=5, inplace=True)

In [26]:
weather_data_2010.isna().sum()

Ozone      0
Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [27]:
weather_data_2010.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month      float64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [28]:
weather_data_2010['Month'] = weather_data_2010['Month'].astype('int')

In [29]:
weather_data_2010.dtypes

Ozone      float64
Solar.R    float64
Wind       float64
Month        int32
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

### 4.3 Data tranformation:

In [30]:
weather_data_2010['Weather'].value_counts()

S     57
C     46
PS    46
Name: Weather, dtype: int64

### 2 Data Transformation Techniques: Discrete Vs Continuous

**1. Dicrete - Label Encoding/ One Hot Encoding**

**2 Continuous - MinMax Scaler/ Standard Scaler/ Robust Scaler**

### 4.3.1  LABEL ENCODING

In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(weather_data_2010['Weather'])

array([2, 0, 1, 2, 1, 0, 1, 2, 1, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0, 1, 0, 1,
       0, 2, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2, 0, 1, 0,
       1, 2, 2, 2, 0, 1, 2, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2, 0, 0, 1, 0,
       1, 2, 2, 2, 0, 1, 2, 2, 0, 1, 0, 2, 2, 0, 1, 1, 0, 2, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 2, 2, 2, 0, 0, 0, 1, 0, 1, 2, 2, 0, 1, 0, 1, 2, 2,
       2, 2, 2, 0, 0, 1, 0, 1, 2, 2, 2, 0, 1, 0, 1, 2, 2, 1, 1, 2, 1, 2,
       0, 1, 1, 2, 2, 0, 1, 0, 1, 2, 1, 2, 0, 1, 2, 2, 0])

In [32]:
weather_data_2010_2 = weather_data_2010.copy()

In [33]:
weather_data_2010_2

     Ozone  Solar.R  Wind  Month  Day  Year  Temp Weather
0     41.0    190.0   7.4      5    1  2010    67       S
1     36.0    118.0   8.0      5    2  2010    72       C
2     12.0    149.0  12.6      5    3  2010    74      PS
3     18.0    313.0  11.5      5    4  2010    62       S
6     23.0    299.0   8.6      5    7  2010    65      PS
..     ...      ...   ...    ...  ...   ...   ...     ...
153   41.0    190.0   7.4      5    1  2010    67       C
154   30.0    193.0   6.9      9   26  2010    70      PS
155   30.5    145.0  13.2      9   27  2010    77       S
156   14.0    191.0  14.3      9   28  2010    75       S
157   18.0    131.0   8.0      9   29  2010    76       C

[149 rows x 8 columns]

In [34]:
weather_data_2010_2['Weather'] = le.fit_transform(weather_data_2010['Weather'])

In [35]:
weather_data_2010_2

     Ozone  Solar.R  Wind  Month  Day  Year  Temp  Weather
0     41.0    190.0   7.4      5    1  2010    67        2
1     36.0    118.0   8.0      5    2  2010    72        0
2     12.0    149.0  12.6      5    3  2010    74        1
3     18.0    313.0  11.5      5    4  2010    62        2
6     23.0    299.0   8.6      5    7  2010    65        1
..     ...      ...   ...    ...  ...   ...   ...      ...
153   41.0    190.0   7.4      5    1  2010    67        0
154   30.0    193.0   6.9      9   26  2010    70        1
155   30.5    145.0  13.2      9   27  2010    77        2
156   14.0    191.0  14.3      9   28  2010    75        2
157   18.0    131.0   8.0      9   29  2010    76        0

[149 rows x 8 columns]

### 4.3.2 ONE HOT ENCODING
It can be built using 2 libraries:

**1. sklearn: OneHotEncoder()**

**2. Pandas: pd.get_dummies()**

In [54]:
weather_data_2010_3 = weather_data_2010.copy()

#### SKLEARN

In [56]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first')
weather_data_2010_3['Weather'] = ohe.fit_transform(weather_data_2010_3['Weather'])
#ohe.fit_transform(weather_data_2010_3['Weather'])

ValueError: Expected 2D array, got 1D array instead:
array=['S' 'C' 'PS' 'S' 'PS' 'C' 'PS' 'S' 'PS' 'S' 'S' 'C' 'S' 'S' 'C' 'PS' 'S'
 'S' 'C' 'PS' 'C' 'PS' 'C' 'S' 'S' 'C' 'PS' 'S' 'C' 'PS' 'C' 'PS' 'C' 'PS'
 'S' 'S' 'S' 'C' 'PS' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'S' 'S' 'C' 'PS' 'S'
 'C' 'PS' 'C' 'PS' 'S' 'S' 'S' 'C' 'PS' 'S' 'S' 'C' 'C' 'PS' 'C' 'PS' 'S'
 'S' 'S' 'C' 'PS' 'S' 'S' 'C' 'PS' 'C' 'S' 'S' 'C' 'PS' 'PS' 'C' 'S' 'C'
 'PS' 'C' 'PS' 'PS' 'C' 'PS' 'C' 'PS' 'S' 'S' 'S' 'C' 'C' 'C' 'PS' 'C'
 'PS' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'S' 'S' 'S' 'S' 'C' 'C' 'PS' 'C' 'PS'
 'S' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'S' 'PS' 'PS' 'S' 'PS' 'S' 'C' 'PS'
 'PS' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'PS' 'S' 'C' 'PS' 'S' 'S' 'C'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [50]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe_1 = pd.DataFrame(ohe.fit_transform(weather_data_2010_3['Weather']).toarray())

weather_data_2010_3 = weather_data_2010_3.join(ohe_1)

ValueError: Expected 2D array, got 1D array instead:
array=['S' 'C' 'PS' 'S' 'PS' 'C' 'PS' 'S' 'PS' 'S' 'S' 'C' 'S' 'S' 'C' 'PS' 'S'
 'S' 'C' 'PS' 'C' 'PS' 'C' 'S' 'S' 'C' 'PS' 'S' 'C' 'PS' 'C' 'PS' 'C' 'PS'
 'S' 'S' 'S' 'C' 'PS' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'S' 'S' 'C' 'PS' 'S'
 'C' 'PS' 'C' 'PS' 'S' 'S' 'S' 'C' 'PS' 'S' 'S' 'C' 'C' 'PS' 'C' 'PS' 'S'
 'S' 'S' 'C' 'PS' 'S' 'S' 'C' 'PS' 'C' 'S' 'S' 'C' 'PS' 'PS' 'C' 'S' 'C'
 'PS' 'C' 'PS' 'PS' 'C' 'PS' 'C' 'PS' 'S' 'S' 'S' 'C' 'C' 'C' 'PS' 'C'
 'PS' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'S' 'S' 'S' 'S' 'C' 'C' 'PS' 'C' 'PS'
 'S' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'S' 'PS' 'PS' 'S' 'PS' 'S' 'C' 'PS'
 'PS' 'S' 'S' 'C' 'PS' 'C' 'PS' 'S' 'PS' 'S' 'C' 'PS' 'S' 'S' 'C'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [36]:
import numpy as np

In [44]:
weather_data_2010_3.reshape(149,-1)

AttributeError: 'DataFrame' object has no attribute 'reshape'

In [46]:
np.reshape(a=weather_data_2010_3, newshape = (149, -1))

,Ozone,Solar.R,Wind,Month,Day,Year,Temp,Weather_C,Weather_PS,Weather_S
0,41.0,190.0,7.4,5.0,1.0,2010.0,67.0,0.0,0.0,1.0
1,36.0,118.0,8.0,5.0,2.0,2010.0,72.0,1.0,0.0,0.0
2,12.0,149.0,12.6,5.0,3.0,2010.0,74.0,0.0,1.0,0.0
3,18.0,313.0,11.5,5.0,4.0,2010.0,62.0,0.0,0.0,1.0
6,23.0,299.0,8.6,5.0,7.0,2010.0,65.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
153,41.0,190.0,7.4,5.0,1.0,2010.0,67.0,1.0,0.0,0.0
154,30.0,193.0,6.9,9.0,26.0,2010.0,70.0,0.0,1.0,0.0
155,30.5,145.0,13.2,9.0,27.0,2010.0,77.0,0.0,0.0,1.0
156,14.0,191.0,14.3,9.0,28.0,2010.0,75.0,0.0,0.0,1.0
157,18.0,131.0,8.0,9.0,29.0,2010.0,76.0,1.0,0.0,0.0

In [40]:
weather_data_2010_3['Weather'].ndim

1

#### PANDAS

In [52]:
weather_data_2010_4 =pd.get_dummies(data = weather_data_2010,  columns= ['Weather'])
weather_data_2010_4

,Ozone,Solar.R,Wind,Month,Day,Year,Temp,Weather_C,Weather_PS,Weather_S
0,41.0,190.0,7.4,5,1,2010,67,0,0,1
1,36.0,118.0,8.0,5,2,2010,72,1,0,0
2,12.0,149.0,12.6,5,3,2010,74,0,1,0
3,18.0,313.0,11.5,5,4,2010,62,0,0,1
6,23.0,299.0,8.6,5,7,2010,65,0,1,0
...,...,...,...,...,...,...,...,...,...,...
153,41.0,190.0,7.4,5,1,2010,67,1,0,0
154,30.0,193.0,6.9,9,26,2010,70,0,1,0
155,30.5,145.0,13.2,9,27,2010,77,0,0,1
156,14.0,191.0,14.3,9,28,2010,75,0,0,1
157,18.0,131.0,8.0,9,29,2010,76,1,0,0